Committer: nico <nico@PC.NICO> 	modified:   README.asciidoc 	renamed:    tools/bash_completion/arkmanager -> tools/bash_completion/dnlmanager 	renamed:    tools/arkmanager -> tools/dnlmanager 	renamed:    tools/arkmanager.cfg -> tools/dnlmanager.cfg 	modified:   tools/install.sh 	modified:   tools/instance.cfg.example 	renamed:    tools/lsb/arkdaemon -> tools/lsb/dnldaemon 	modified:   tools/migrate-config.sh 	modified:   tools/migrate-main-instance.sh 	renamed:    tools/openrc/arkdaemon -> tools/openrc/dnldaemon 	renamed:    tools/redhat/arkdaemon -> tools/redhat/dnldaemon 	deleted:    tools/systemd/arkmanager.service 	deleted:    tools/systemd/arkmanager@.service 	renamed:    tools/systemd/arkmanager.init -> tools/systemd/dnlmanager.init 	new file:   tools/systemd/dnlmanager.service 	new file:   tools/systemd/dnlmanager@.service 	modified:   tools/uninstall-user.sh 	modified:   tools/uninstall.sh 	renamed:    tools/upstart/arkmanager-instance.conf -> tools/upstart/dnlmanager-instance.conf 	renamed:    tools/upstart/arkmanager.conf -> tools/upstart/dnlmanager.conf

diff --git a/tools/redhat/dnldaemon b/tools/redhat/dnldaemon
--- a/tools/redhat/dnldaemon
+++ b/tools/redhat/dnldaemon
@@ -1,24 +1,38 @@
 #!/bin/bash
+#
+# /etc/rc.d/init.d/dnlmanager
+#
+# dnl manager daemon
+#
+# chkconfig: 2345 80 20
+# description: dnl manager daemon used to start the server and keep it updated
+# processname: ShooterGameServer
+# config: /etc/dnlmanager/dnlmanager.cfg
+
 ### BEGIN INIT INFO
-# Provides:          ARK manager deamon
+# Provides:          dnl manager deamon
 # Required-Start:    networking
 # Required-Stop:     networking
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: ARK manager deamon
-# Description:       ARK manager daemon used to start the server and keep it updated
+# Short-Description: dnl manager deamon
+# Description:       dnl manager daemon used to start the server and keep it updated
 #
 ### END INIT INFO
 
 # Using the lsb functions to perform the operations.
-. /lib/lsb/init-functions
+. /etc/rc.d/init.d/functions
 
 # Global variables
-source /etc/arkmanager/arkmanager.cfg
+source /etc/dnlmanager/dnlmanager.cfg
 
 NAME="ShooterGameServer"
 LOGFILE="${logdir}/${NAME}.log"
-DAEMON="/usr/bin/arkmanager"
+DAEMON="/usr/bin/dnlmanager"
+
+GREEN="\\033[1;32m"
+RED="\\033[1;31m"
+NORMAL="\\033[0;39m"
 
 SVCNAME="${0##*/}"
 INSTANCE="${SVCNAME#*.}"
@@ -34,25 +48,26 @@ test -x $DAEMON || exit 5
 
 function start_instance(){
   local INSTANCE="$1"
-  PID="$(<"/var/run/arkmanager.${INSTANCE}.pid")"
+  PID="$(<"/var/run/dnlmanager.${INSTANCE}.pid")"
   if [ -n "$PID" ] && kill -0 "$PID" >/dev/null 2>&1; then
     if grep " ${PID} .* ${DAEMON}" <(ps -ef) >/dev/null 2>&1; then
       echo "$NAME @${INSTANCE} is already running"
       return 0
     fi
   fi
-  log_daemon_msg "Starting" "$NAME @${INSTANCE}"
+  echo -n "Starting $NAME @${INSTANCE}: "
   ulimit -n 100000
   "${DAEMON}" run "@${INSTANCE}" &
   PID="$!"
 
   sleep 5
   if kill -0 "$PID" >/dev/null 2>&1; then
-    echo "$PID" >"/var/run/arkmanager.${INSTANCE}.pid"
-    log_end_msg 0
+    echo "$PID" >"/var/run/dnlmanager.${INSTANCE}.pid"
+    touch "/var/lock/subsys/dnlmanager.${INSTANCE}"
+    echo "[" "$GREEN" " OK " "$NORMAL" "]"
     return 0
   else
-    log_end_msg 1
+    echo "[" "$RED" " FAILED " "$NORMAL" "]"
     return 1
   fi
 }
@@ -73,10 +88,11 @@ function start_all_instances(){
 
 function stop_instance(){
   local INSTANCE="$1"
-  log_daemon_msg "Stopping $NAME @${INSTANCE}: "
+  echo -n "Stopping $NAME @${INSTANCE}: "
   "${DAEMON}" stop "@${INSTANCE}" &
-  rm -f "/var/run/arkmanager.${INSTANCE}.pid"
-  log_end_msg 0
+  rm -f "/var/lock/subsys/dnlmanager.${INSTANCE}"
+  rm -f "/var/run/dnlmanager.${INSTANCE}.pid"
+  echo "[" "$GREEN" " OK " "$NORMAL" "]"
   return 0
 }
 
@@ -87,6 +103,7 @@ case "$1" in
       exit $?
     else
       if start_all_instances; then
+        touch /var/lock/subsys/dnlmanager
         exit 0
       else
         exit 1
@@ -102,6 +119,7 @@ case "$1" in
       for instance in $("${DAEMON}" list-instances --brief); do
         stop_instance "$instance"
       done
+      rm -f "/var/lock/subsys/dnlmanager"
       exit $?
     fi
   ;;
@@ -113,13 +131,12 @@ case "$1" in
 
   status)
     "$DAEMON" status "@${INSTANCE:-all}"
+    exit 0
   ;;
 
   *)
     # For invalid arguments, print the usage message.
     echo "Usage: $0 {start|stop|restart|status}"
-    exit 2
+    exit 1
   ;;
 esac
-
-exit 0
